# Generated by Django 5.0.2 on 2024-02-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_cat_alter_service_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.cat'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.cat'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.subcategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.type'),
        ),
    ]
