# Generated by Django 5.0.2 on 2024-02-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urbanImage', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'urban',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(choices=[('Kolhapur', 'Kolhapur'), ('Mumbai', 'Mumbai'), ('Surat', 'Surat'), ('Ahmedabad', 'Ahmedabad'), ('Pune', 'Pune'), ('Gandhinagar', 'Gandhinagar')], max_length=255),
        ),
    ]
