# Generated by Django 5.0.2 on 2024-03-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
