# Generated by Django 5.0.2 on 2024-03-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_booking_invoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
